AnketMerkezi.UI/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnketMerkezi.Data.ORM.Entities;
using AnketMerkezi.UI.Models.Managers;
using AnketMerkezi.UI.Models.Types;
using AnketMerkezi.UI.Models.VMs.Survey;
using Microsoft.AspNetCore.Mvc;

namespace AnketMerkezi.UI.Controllers
{
    public class SurveyController : BaseController
    {
        public IActionResult Index()
        {
            int webUserID = int.Parse(GetWebUserID());
            List<SurveyIndexVM> model = new List<SurveyIndexVM>();

            List<Survey> userSurveys = RedisService.Survey.GetList(webUserID + "-Survey-Index-List");
            List<SurveyVisit> userSurveyVisits = RedisService.SurveyVisit.GetList(webUserID + "-Survey-Index-VisitList");
            if (userSurveys == null && userSurveyVisits == null)
            {
                userSurveys = Service.Survey.GetAllWithQuery(x => x.UserID == webUserID);
                userSurveyVisits = Service.SurveyVisit.GetAllWithQuery(x => userSurveys.FirstOrDefault(y => y.ID == x.SurveyID) != null).ToList();

                RedisService.Survey.SaveList(webUserID + "-Survey-Index-List", userSurveys, 30);
                RedisService.SurveyVisit.SaveList(webUserID + "-Survey-Index-VisitList", userSurveyVisits, 30);
            }

            model = userSurveys.Select(x => new SurveyIndexVM
            {
                ID = x.ID,
                AnswerCount = userSurveyVisits.Where(y => y.SurveyID == y.ID).Sum(y => y.SurveyVisitAnswers.Count),
                Name = x.Name,
                IsActive = x.IsActive,
                AddDateText = DateManager.FormatDate(x.AddDate),
                AddDate = x.AddDate,
                Link = x.LinkCode
            }).OrderByDescending(x => x.AddDate).ToList();

            return View(model);
        }

        public IActionResult Edit(string link)
        {
            int webUserID = int.Parse(GetWebUserID());
            Survey survey = Service.Survey.FirstOrDefault(x => x.LinkCode == link && x.UserID == webUserID);
            if (survey == null)
            {
                TempData["OperationStatus"] = EnumOperationStatus.Failure;
                return RedirectToAction("Index");
            }


            return View();
        }

        public IActionResult Add()
        {
            int webUserID = int.Parse(GetWebUserID());
            User user = Service.User.FirstOrDefault(x => x.ID == webUserID);
            int quota = user.AccountType == (int)EnumUserType.Normal ? 1 : user.AccountType == (int)EnumUserType.Silver ? 3 : user.AccountType == (int)EnumUserType.Gold ? 5 : 0;
            if (Service.Survey.GetAllWithQuery(x => x.UserID == webUserID && x.IsActive).Count >= quota)
            {
                TempData["OperationStatus"] = EnumOperationStatus.Failure;
                TempData["OperationStatusMessage"] = "Anket kotanız dolduğu için anket oluşturamazsınız.";
                return RedirectToAction("Index");
            }

            return View(new SurveyAdd(1));
        }

        public IActionResult Preview(string link)
        {
            int webUserID = int.Parse(GetWebUserID());
            Survey survey = Service.Survey.FirstOrDefault(x => x.LinkCode == link && x.UserID == webUserID);
            if (survey == null)
            {
                TempData["OperationStatus"] = EnumOperationStatus.Failure;
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Share()
        {
            return View();
        }

        public IActionResult ChangeStatus(int id)
        {
            int webUserID = int.Parse(GetWebUserID());
            Survey survey = Service.Survey.FirstOrDefault(x => x.ID == id);
            if (survey != null && survey.UserID == webUserID)
            {
                survey.IsActive = survey.IsActive == true ? false : true;
                Service.Survey.Update(survey);

                TempData["OperationStatus"] = EnumOperationStatus.Success;
            }
            else
                TempData["OperationStatus"] = EnumOperationStatus.Failure;

            ClearCache();
            return RedirectToAction("Index");
        }

        private void ClearCache()
        {
            string webUserID = GetWebUserID();
            RedisService.Survey.Delete(webUserID + "-Survey-Index-List");
            RedisService.Survey.Delete(webUserID + "-Survey-Index-VisitList");
        }

    }
}

AnketMerkezi.UI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AnketMerkezi.Data.ORM.Entities;
using AnketMerkezi.UI.Models.VMs.User;
using AnketMerkezi.UI.Models.Types;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace AnketMerkezi.UI.Controllers
{
    [AllowAnonymous]
    public class UserController : BaseController
    {
        public int UsernameControl(string username)
        {
            User user = Service.User.FirstOrDefault(x => x.Username == username);
            if (user == null)
                return 0;
            else
                return 1;
        }

        public int EmailControl(string email)
        {
            UserDetail user = Service.UserDetail.FirstOrDefault(x => x.Email == email);
            if (user == null)
                return 0;
            else
                return 1;
        }

        public IActionResult Register() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public int Register(RegisterVM model)
        {
            if (ModelState.IsValid)
            {
                User user = Service.User.FirstOrDefault(x => x.Username == model.Username);
                UserDetail userDetail = Service.UserDetail.FirstOrDefault(x => x.Email == model.Email);
                if (user == null && userDetail == null)
                {
                    user = Service.User.Insert(new User { AccountType = (int)EnumUserType.Normal, Username = model.Username, Password = model.Password });
                    Service.UserDetail.Insert(new UserDetail { Email = model.Email, Name = model.Name, PhoneNumber = model.PhoneNumber, Surname = model.Surname, UserID = user.ID });
                    return 1;
                }
                else
                    return 0;
            }
            else
                return 0;
        }

        public IActionResult Login() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginVM model)
        {
            if (ModelState.IsValid)
            {
                User user = Service.User.FirstOrDefault(x => x.Username == model.Username && x.Password == model.Password);
                if (user != null)
                {
                    var claims = new List<Claim>
                     {
                        new Claim(ClaimTypes.Name, user.Username),
                        new Claim(ClaimTypes.Role, user.AccountType.ToString()),
                        new Claim(ClaimTypes.NameIdentifier, user.ID.ToString())
                    };

                    var userIdentity = new ClaimsIdentity(claims, "login");

                    await HttpContext.SignInAsync(new ClaimsPrincipal(userIdentity));

                    return RedirectToAction("Index", "Panel");
                }
                else
                    ViewBag.msg = "Kullanıcı adınız veya şifreniz yanlıştır.";
            }
            else
                ViewBag.msg = "Lütfen geçerli veri girişi yapınız.";
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

AnketMerkezi.UI/Views/Shared/_PanelLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Anket Merkezi - Panel | @ViewBag.Title</title>

    <link href="~/PanelDesign/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/PanelDesign/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/PanelDesign/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="~/PanelDesign/css/sb-admin.css" rel="stylesheet">
    <link href="~/PanelDesign/vendor/fakeLoader/fakeloader.css" rel="stylesheet" />

</head>
<body id="page-top">


    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="index.html">Anket Merkezi</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0"></form>
        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">

            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="@Url.Action("Settings","Panel")">Ayarlar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("Logout","User")">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Panel")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Genel Durum</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-fw fa-poll"></i>
                    <span>Anket İşlemleri</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                    <a class="dropdown-item" href="@Url.Action("Index","Survey")"><i class="fa fa-list-ul"></i> Anket Listesi</a>
                    <a class="dropdown-item" href="@Url.Action("Add","Survey")"><i class="fa fa-plus"></i> Anket Ekle</a>
                    <a class="dropdown-item" href="@Url.Action("Share","Survey")"><i class="fa fa-share-alt"></i> Anket Paylaş</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-fw fa-headset"></i>
                    <span>Destek Talep</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                    <a class="dropdown-item" href="@Url.Action("Index","SupportRequest")"><i class="fa fa-list-ul"></i> Destek Talep Listesi</a>
                    <a class="dropdown-item" href="@Url.Action("Add","SupportRequest")"><i class="fa fa-plus"></i> Destek Talebi Ekle</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("UsageQuota","Panel")">
                    <i class="fas fa-fw fa-spinner"></i>
                    <span>Kullanım Kotası</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("UpgradeAccount","Panel")">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Hesap Yükselt</span>
                </a>
            </li>
        </ul>
        <div id="content-wrapper">
            <div class="container-fluid">

                @RenderBody()


            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Tüm hakları saklıdır © Anket Merkezi 2018</span>
                    </div>
                </div>
            </footer>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <script src="~/PanelDesign/vendor/jquery/jquery.min.js"></script>
    <script src="~/PanelDesign/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/PanelDesign/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/PanelDesign/vendor/chart.js/Chart.min.js"></script>
    <script src="~/PanelDesign/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/PanelDesign/vendor/datatables/dataTables.bootstrap4.js"></script>
    <script src="~/PanelDesign/js/sb-admin.min.js"></script>
    <script src="~/PanelDesign/js/demo/datatables-demo.js"></script>
    <script src="~/PanelDesign/js/demo/chart-area-demo.js"></script>
    <script src="~/PanelDesign/vendor/fakeLoader/fakeloader.min.js"></script>
    <script type="text/javascript">
        $(".load").click(() => {
            window.FakeLoader.init({ auto_hide: false });
        });
    </script>

</body>
</html>